#!/usr/bin/env ruby

case ARGV[0]
when 'test'
  system 'cd ~/cachelab-handout2 && make'
  exit $?.exitstatus
when 'score'
  system 'cd ~/cachelab-handout2 && make'
  exit $?.exitstatus unless $?.success?

  def test m, n
    result = `cd ~/cachelab-handout2 && ./test-trans -M #{m} -N #{n}`
    /^TEST_TRANS_RESULTS=1:(.*)$/.match(result)[1]
  end

  puts "     300 <  #{test(32, 32)} <  600"
  puts "    1300 < #{test(64, 64)} < 2000"
  puts "    2000 < #{test(61, 67)} < 3000"
  exit
else
  puts <<-HELP
Usage: ./do <command>

Commands:
    test        Test if everything's fine
    score       Get score of it
  HELP
end
