#!/usr/bin/env ruby
require 'zlib'
require 'diffy'

print 'Compiling ... '
msg = `javac BigInteger.java 2>&1`
unless $?.success?
  puts "Failed\n\n\e[33m#{msg}\n\e[31mCompile Error\e[0m"
  exit 1
end
puts 'Done'

print 'Testing ... '
actual = `gzcat input.gz | java BigInteger`
expected = Zlib::GzipReader.open('output.gz').read
unless actual == expected
  Diffy::Diff.default_format = :color
  puts 'Failed'
  puts ''
  puts Diffy::Diff.new(expected, actual)
  exit 1
end
puts 'Succeeded'
