#!/usr/bin/env ruby

case ARGV[0]
when 'test'
  system 'cd ~/cachelab-handout2 && make'
  exit $?.exitstatus
when 'score'
  system <<-SCORE
    cd ~/cachelab-handout2 &&
    make &&
    ./test-trans -M 32 -N 32 &&
    ./test-trans -M 64 -N 64 &&
    ./test-trans -M 61 -N 67
  SCORE
  exit $?.exitstatus
else
  puts <<-HELP
Usage: ./do <command>

Commands:
    test        Test if everything's fine
    score       Get score of it
  HELP
end
